### ISSUE TITLE
Missing requirements.txt file

### ISSUE THREAD

**Issue by jonathanbaugh** [ChrisDolph/scrape_city_jobs_site#3]
To be able to run the software we need to install packages. Python's package manager, pip, has an easy way to create these files.

You'll want to create a requirements.txt file using `pip freeze`

It's also very useful to use virtual environments which can be created and destroyed to make sure you have all of your dependencies listed.

**Comment by jonathanbaugh** [comment]
PR: https://github.com/ChrisDolph/scrape_city_jobs_site/pull/4

**Comment by ChrisDolph** [comment]
Thanks Jon.
