### ISSUE TITLE
PEP8 and Pylint errors

### ISSUE THREAD

**Issue by jonathanbaugh** [ChrisDolph/scrape_city_jobs_site#5]
PEP8 and PyLint are generally a good practice. PEP8 is going to check your code for formatting issues. PyLint goes a lot deeper into analyzing your code for the problems it's able to find.

**Comment by jonathanbaugh** [comment]
PR: https://github.com/ChrisDolph/scrape_city_jobs_site/pull/6

**Comment by ChrisDolph** [comment]
Valid changes. Merged.
